
package Presentacion;
import dominio.CalcularEtapas;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

public class VistaCalcularEtapas extends javax.swing.JFrame {
    
    CalcularEtapas etapa_Calculada= new CalcularEtapas();
    String fechaInicio ;
        String fechaFin ;
        String deporte;
        String rama ;
        String jefeRama;
        String entAux ;
        String metodologo ;
        int totalSem ;
        
    public VistaCalcularEtapas(String fechaInicio, String fechaFin, String deporte, String rama, String jefeRama, String entAux, String metodologo, int totalSem) {
           initComponents();
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.deporte = deporte;
        this.rama = rama;
        this.jefeRama = jefeRama;
        this.entAux = entAux;
        this.metodologo = metodologo;
        this.totalSem = totalSem;
    }

    public VistaCalcularEtapas() {
        initComponents();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImagenPotrosLabel = new javax.swing.JLabel();
        TituloLabel = new javax.swing.JLabel();
        tipo_EtapaLabel = new javax.swing.JLabel();
        tipo_EtapaText = new javax.swing.JTextField();
        SemanasLabel = new javax.swing.JLabel();
        SemanasText = new javax.swing.JTextField();
        MinLabel = new javax.swing.JLabel();
        MinText = new javax.swing.JTextField();
        MaxLabel = new javax.swing.JLabel();
        MaxText = new javax.swing.JTextField();
        PromLabel = new javax.swing.JLabel();
        PromText = new javax.swing.JTextField();
        InsLabel = new javax.swing.JLabel();
        InsText = new javax.swing.JTextField();
        VolumenEtapaLabel = new javax.swing.JLabel();
        VolumenEtapaText = new javax.swing.JTextField();
        ButtonEnviar = new javax.swing.JButton();
        BtnRegresar = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        LabelMedioFisico = new javax.swing.JLabel();
        FondoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calcular Etapas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagenPotrosLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PotrosChico.jpg"))); // NOI18N
        getContentPane().add(ImagenPotrosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        TituloLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TituloLabel.setText("       INSTITUTO TECNOLOGICO DE SONORA DEPARTAMENTO DE DEPORTE Y SALUD ");
        TituloLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));
        getContentPane().add(TituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 810, -1));

        tipo_EtapaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipo_EtapaLabel.setText("Tipo Etapa:");
        getContentPane().add(tipo_EtapaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        tipo_EtapaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_EtapaTextActionPerformed(evt);
            }
        });
        getContentPane().add(tipo_EtapaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 80, -1));

        SemanasLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SemanasLabel.setText("Semanas:");
        getContentPane().add(SemanasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        SemanasText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SemanasTextActionPerformed(evt);
            }
        });
        getContentPane().add(SemanasText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 40, -1));

        MinLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MinLabel.setText("Min:");
        getContentPane().add(MinLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        MinText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinTextActionPerformed(evt);
            }
        });
        getContentPane().add(MinText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 40, -1));

        MaxLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MaxLabel.setText("Max:");
        getContentPane().add(MaxLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, -1));

        MaxText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaxTextActionPerformed(evt);
            }
        });
        getContentPane().add(MaxText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 40, -1));

        PromLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PromLabel.setText("Prom:");
        getContentPane().add(PromLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, -1));

        PromText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PromTextActionPerformed(evt);
            }
        });
        getContentPane().add(PromText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 40, -1));

        InsLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        InsLabel.setText("Ins:");
        getContentPane().add(InsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, -1, -1));

        InsText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsTextActionPerformed(evt);
            }
        });
        getContentPane().add(InsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 40, -1));

        VolumenEtapaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        VolumenEtapaLabel.setText("Volumen Etapa:");
        getContentPane().add(VolumenEtapaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, -1));

        VolumenEtapaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumenEtapaTextActionPerformed(evt);
            }
        });
        getContentPane().add(VolumenEtapaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 40, -1));

        ButtonEnviar.setText("Enviar");
        ButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 70, -1));

        BtnRegresar.setText("Regresar");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 80, -1));

        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 80, -1));

        LabelMedioFisico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(LabelMedioFisico, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 290, 30));

        FondoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BlueWallpaper.jpeg"))); // NOI18N
        getContentPane().add(FondoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tipo_EtapaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_EtapaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_EtapaTextActionPerformed

    private void SemanasTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SemanasTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SemanasTextActionPerformed

    private void MinTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MinTextActionPerformed

    private void MaxTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaxTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaxTextActionPerformed

    private void PromTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PromTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PromTextActionPerformed

    private void VolumenEtapaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumenEtapaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VolumenEtapaTextActionPerformed

    private void InsTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsTextActionPerformed

    private void ButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEnviarActionPerformed
        // TODO add your handling code here:
        
        float MinText,MaxText,PromText,VolumenEtapaText;
        int InsText,SemanasText; 
        String tipo_EtapaText;
        
        tipo_EtapaText=this.tipo_EtapaText.getText();
        SemanasText=Integer.parseInt(this.SemanasText.getText());
        MinText=Float.parseFloat(this.MinText.getText());
        MaxText=Float.parseFloat(this.MaxText.getText());
        
        PromText=(MinText+MaxText)/2;
        InsText=Integer.parseInt(this.InsText.getText());
        
        VolumenEtapaText=PromText*InsText*SemanasText;
            
        etapa_Calculada.setIns(InsText);
        etapa_Calculada.setMax(MaxText);
        etapa_Calculada.setMin(MinText);
        etapa_Calculada.setProm(PromText);
        etapa_Calculada.setSemanas(SemanasText);
        etapa_Calculada.setTipoEtapa(tipo_EtapaText);
        etapa_Calculada.setVolumenEtapa(VolumenEtapaText);
        
        
    }//GEN-LAST:event_ButtonEnviarActionPerformed

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        ConfigInicial config=new ConfigInicial();
        this.dispose();
        config.setVisible(true);
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed

        // TODO add your handling code here:
        tipo_EtapaText.setText("");
        SemanasText.setText("");
        InsText.setText("");
        MaxText.setText("");
        MinText.setText("");
        PromText.setText("");
        VolumenEtapaText.setText("");
        
        
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    public CalcularEtapas getEtapa_Calculada() {
        return etapa_Calculada;
    }

    public void setEtapa_Calculada(CalcularEtapas etapa_Calculada) {
        this.etapa_Calculada = etapa_Calculada;
    }

    public JButton getBtnLimpiar() {
        return BtnLimpiar;
    }

    public void setBtnLimpiar(JButton BtnLimpiar) {
        this.BtnLimpiar = BtnLimpiar;
    }

    public JButton getBtnRegresar() {
        return BtnRegresar;
    }

    public void setBtnRegresar(JButton BtnRegresar) {
        this.BtnRegresar = BtnRegresar;
    }

    public JButton getButtonEnviar() {
        return ButtonEnviar;
    }

    public void setButtonEnviar(JButton ButtonEnviar) {
        this.ButtonEnviar = ButtonEnviar;
    }

    public JLabel getFondoLabel() {
        return FondoLabel;
    }

    public void setFondoLabel(JLabel FondoLabel) {
        this.FondoLabel = FondoLabel;
    }

    public JLabel getImagenPotrosLabel() {
        return ImagenPotrosLabel;
    }

    public void setImagenPotrosLabel(JLabel ImagenPotrosLabel) {
        this.ImagenPotrosLabel = ImagenPotrosLabel;
    }

    public JLabel getInsLabel() {
        return InsLabel;
    }

    public void setInsLabel(JLabel InsLabel) {
        this.InsLabel = InsLabel;
    }

    public JTextField getInsText() {
        return InsText;
    }

    public void setInsText(JTextField InsText) {
        this.InsText = InsText;
    }

    public JLabel getLabelMedioFisico() {
        return LabelMedioFisico;
    }

    public void setLabelMedioFisico(JLabel LabelMedioFisico) {
        this.LabelMedioFisico = LabelMedioFisico;
    }

    public JLabel getMaxLabel() {
        return MaxLabel;
    }

    public void setMaxLabel(JLabel MaxLabel) {
        this.MaxLabel = MaxLabel;
    }

    public JTextField getMaxText() {
        return MaxText;
    }

    public void setMaxText(JTextField MaxText) {
        this.MaxText = MaxText;
    }

    public JLabel getMinLabel() {
        return MinLabel;
    }

    public void setMinLabel(JLabel MinLabel) {
        this.MinLabel = MinLabel;
    }

    public JTextField getMinText() {
        return MinText;
    }

    public void setMinText(JTextField MinText) {
        this.MinText = MinText;
    }

    public JLabel getPromLabel() {
        return PromLabel;
    }

    public void setPromLabel(JLabel PromLabel) {
        this.PromLabel = PromLabel;
    }

    public JTextField getPromText() {
        return PromText;
    }

    public void setPromText(JTextField PromText) {
        this.PromText = PromText;
    }

    public JLabel getSemanasLabel() {
        return SemanasLabel;
    }

    public void setSemanasLabel(JLabel SemanasLabel) {
        this.SemanasLabel = SemanasLabel;
    }

    public JTextField getSemanasText() {
        return SemanasText;
    }

    public void setSemanasText(JTextField SemanasText) {
        this.SemanasText = SemanasText;
    }

    public JLabel getTituloLabel() {
        return TituloLabel;
    }

    public void setTituloLabel(JLabel TituloLabel) {
        this.TituloLabel = TituloLabel;
    }

    public JLabel getVolumenEtapaLabel() {
        return VolumenEtapaLabel;
    }

    public void setVolumenEtapaLabel(JLabel VolumenEtapaLabel) {
        this.VolumenEtapaLabel = VolumenEtapaLabel;
    }

    public JTextField getVolumenEtapaText() {
        return VolumenEtapaText;
    }

    public void setVolumenEtapaText(JTextField VolumenEtapaText) {
        this.VolumenEtapaText = VolumenEtapaText;
    }

    public JLabel getTipo_EtapaLabel() {
        return tipo_EtapaLabel;
    }

    public void setTipo_EtapaLabel(JLabel tipo_EtapaLabel) {
        this.tipo_EtapaLabel = tipo_EtapaLabel;
    }

    public JTextField getTipo_EtapaText() {
        return tipo_EtapaText;
    }

    public void setTipo_EtapaText(JTextField tipo_EtapaText) {
        this.tipo_EtapaText = tipo_EtapaText;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JButton ButtonEnviar;
    private javax.swing.JLabel FondoLabel;
    private javax.swing.JLabel ImagenPotrosLabel;
    private javax.swing.JLabel InsLabel;
    private javax.swing.JTextField InsText;
    private javax.swing.JLabel LabelMedioFisico;
    private javax.swing.JLabel MaxLabel;
    private javax.swing.JTextField MaxText;
    private javax.swing.JLabel MinLabel;
    private javax.swing.JTextField MinText;
    private javax.swing.JLabel PromLabel;
    private javax.swing.JTextField PromText;
    private javax.swing.JLabel SemanasLabel;
    private javax.swing.JTextField SemanasText;
    private javax.swing.JLabel TituloLabel;
    private javax.swing.JLabel VolumenEtapaLabel;
    private javax.swing.JTextField VolumenEtapaText;
    private javax.swing.JLabel tipo_EtapaLabel;
    private javax.swing.JTextField tipo_EtapaText;
    // End of variables declaration//GEN-END:variables
}
