/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Lógica.DistribucionVolumenNegocio;
import dominio.DistribucionVolumen;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import persistence.DistribucionVolumenDAO;


/**
 *
 * @author jonyo
 */
public class VistaDistribucionVolumen extends javax.swing.JFrame {
    DefaultTableModel modelo;
    public DistribucionVolumenDAO distribucion= new DistribucionVolumenDAO();


    public VistaDistribucionVolumen() {
        initComponents();
        
        setLocationRelativeTo(null); 
        setTitle("Distribución Volumen");
        
        modelo = new DefaultTableModel();
        modelo.addColumn("Id");
        modelo.addColumn("Etapa");
        modelo.addColumn("Semana");
        modelo.addColumn("Fecha Inicio");
        modelo.addColumn("Fecha Fin");
        modelo.addColumn("Mesociclo");
        modelo.addColumn("Ciclicidad");
        modelo.addColumn("Acentos");
        modelo.addColumn("Medios Fisicos");
        modelo.addColumn("Esfuerzo");

        this.TablaDistribucionVolumen.setModel(modelo);
        LlenarTabla();
    }
    
    public void LLenarTablaDist (){
    DistribucionVolumenNegocio distribucionVolumenNegocio = new DistribucionVolumenNegocio();
    List<DistribucionVolumen> listaDistribucionVolumen = distribucionVolumenNegocio.obtenerInformacionDistribucionVolumen();

    String[] columnas = new String[]{"ID", "Etapa", "Semana", "Mesociclo", "Fecha Inicio", "Fecha Fin", "Ciclicidad", "Acentos", "Esfuerzo", "Medios Físicos"};
    DefaultTableModel modelo = new DefaultTableModel(columnas, 0);

    for (DistribucionVolumen distribucion : listaDistribucionVolumen) {
        modelo.addRow(new Object[]{
            distribucion.getId(),
            distribucion.getEtapa(),
            distribucion.getSemanaa(),
            distribucion.getMesociclo(),
            distribucion.getFechaInicio(),
            distribucion.getFechaFin(),
            distribucion.getCiclicidad(),
            distribucion.getAcentos(),
            distribucion.getEsfuerzo(),
            distribucion.getMediosFisicos()
        });
        }
    }

    public void LlenarTabla (){
        List<DistribucionVolumen> list = distribucion.consulTodo();
        DefaultTableModel model= (DefaultTableModel) TablaDistribucionVolumen.getModel();
        int rowCount = model.getRowCount();
        
        for(int m=rowCount-1;m>=0;m--)
        {
           model.removeRow(m);
        }
        
         Object rowData[]=new Object[10];
        for(int i=0; i<list.size();i++){
            rowData[0]=list.get(i).id;
            rowData[1]=list.get(i).etapa;
            rowData[2]=list.get(i).semana;
            rowData[3]=list.get(i).fechaInicio;
            rowData[4]=list.get(i).fechaFin;
             rowData[5]=list.get(i).mesociclo;
            rowData[6]=list.get(i).ciclicidad;
            rowData[7]=list.get(i).acentos;
            rowData[8]=list.get(i).mediosFisicos;
            rowData[9]=list.get(i).esfuerzo;
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDistribucionVolumen = new javax.swing.JTable();
        IconoPotrosLabel = new javax.swing.JLabel();
        NombreLabel = new javax.swing.JLabel();
        FondoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Distribucion Volumen");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TituloLabel.setText("       INSTITUTO TECNOLOGICO DE SONORA DEPARTAMENTO DE DEPORTE Y SALUD ");
        TituloLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));
        getContentPane().add(TituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 570, -1));

        TablaDistribucionVolumen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaDistribucionVolumen);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 800, 390));

        IconoPotrosLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PotrosChico.jpg"))); // NOI18N
        getContentPane().add(IconoPotrosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        NombreLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        NombreLabel.setText("Plan Grafico");
        getContentPane().add(NombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        FondoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BlueWallpaper.jpeg"))); // NOI18N
        getContentPane().add(FondoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 816, 499));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoLabel;
    private javax.swing.JLabel IconoPotrosLabel;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JTable TablaDistribucionVolumen;
    private javax.swing.JLabel TituloLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
